const EVENTS = {
  ACTION: {
    WAITING_ROOM: "WAITING_ROOM",
    WAITING_ROOM_SIT: "WAITING_ROOM_SIT",
    WAITING_ROOM_READY: "WAITING_ROOM_READY",
    WAITING_ROOM_CANCEL: "WAITING_ROOM_CANCEL",
    WAITING_ROOM_START: "WAITING_ROOM_START",
    WAITING_ROOM_PLAY: "WAITING_ROOM_PLAY",
    WAITING_ROOM_KICKPLAYER: "WAITING_ROOM_KICKPLAYER",
    WAITING_ROOM_ITEMBURN: "WAITING_ROOM_ITEMBURN",
    LOBBY_IN: "LOBBY_IN",
    LOBBY_SEARCH: "LOBBY_SEARCH",
    WAITING_ROOM_DATA_ROLLBACK: "WAITING_ROOM_DATA_ROLLBACK",
    WAITING_ROOM_TRANSACTION_PROCESS: "WAITING_ROOM_TRANSACTION_PROCESS",
    CHAT_SEND_MESSAGE: "CHAT_SEND_MESSAGE"
  },
  LISTENERS: {
    WAITING_ROOM_ONLINE: "WAITING_ROOM_ONLINE",
    WAITING_ROOM_COUNTDOWN: "WAITING_ROOM_COUNTDOWN",
    LOBBY_ONLINE: "LOBBY_ONLINE",
    WAITING_ROOM_KICK: "WAITING_ROOM_KICK",
    WAITING_ROOM_ITEM: "WAITING_ROOM_ITEM",
    WAITING_ROOM_ROLLBACK: "WAITING_ROOM_ROLLBACK",
    WAITING_ROOM_TIMEOUT: "WAITING_ROOM_TIMEOUT",
    LOBBY_SEARCH_DATA: "LOBBY_SEARCH_DATA",
    ROOM_MESSAGE: "ROOM_MESSAGE"
  }
}

export default EVENTS
