const CONFIGS = {
  MODE: process.env.NEXT_PUBLIC_MODE,
  APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  KEYTEXT: process.env.NEXT_PUBLIC_KEYTEXT,
  KEY_RECAPTCHA: process.env.NEXT_PUBLIC_KEY_RECAPTCHA,
  BASE_URL: {
    API: process.env.NEXT_PUBLIC_API_URL,
    GAME: process.env.NEXT_PUBLIC_GAME_URL,
    FRONTEND: process.env.NEXT_PUBLIC_FRONTEND_URL,
    SUPPORT: process.env.NEXT_PUBLIC_SUPPORT,
    MARKETPLACE: process.env.NEXT_PUBLIC_MARKETPLACE,
    NAKAVERSE: process.env.NEXT_PUBLIC_NAKAVERSE,
    REDEEM: process.env.NEXT_PUBLIC_REDEEM,
    BINANCE_API: process.env.NEXT_PUBLIC_API_BINANCE
  },
  CONTRACT_ADDRESS: {
    ERC20: process.env.NEXT_PUBLIC_CONTRACT_ERC20,
    OWNER: process.env.NEXT_PUBLIC_OWNER,
    BALANCE_VAULT: process.env.NEXT_PUBLIC_CONTRACT_BALANCE_VAULT,
    BALANCE_VAULT_BINANCE:
      process.env.NEXT_PUBLIC_CONTRACT_BALANCE_VAULT_BINANCE,
    ITEM_VAULT: process.env.NEXT_PUBLIC_CONTRACT_ITEM_VAULT,
    SHOP: process.env.NEXT_PUBLIC_CONTRACT_SHOP,
    MARKETPLACE: process.env.NEXT_PUBLIC_CONTRACT_MARKETPLACE,
    MARKETPLACE_NFT: process.env.NEXT_PUBLIC_CONTRACT_MARKETPLACE_NFT,
    LAND_NFT: process.env.NEXT_PUBLIC_CONTRACT_LAND_NFT,
    NAKA: process.env.NEXT_PUBLIC_NAKA_CONTRACT,
    GETALLLANDSOFADDRESS: process.env.NEXT_PUBLIC_CONTRACT_GETALLLANDSOFADDRESS,
    STAKING_30DAY: process.env.NEXT_PUBLIC_CONTRACT_STAKING_30DAY,
    STAKING_60DAY: process.env.NEXT_PUBLIC_CONTRACT_STAKING_60DAY,
    STAKING_90DAY: process.env.NEXT_PUBLIC_CONTRACT_STAKING_90DAY,
    STAKING_A_30DAY: process.env.NEXT_PUBLIC_CONTRACT_STAKING_A_30DAY,
    STAKING_A_60DAY: process.env.NEXT_PUBLIC_CONTRACT_STAKING_A_60DAY,
    STAKING_A_90DAY: process.env.NEXT_PUBLIC_CONTRACT_STAKING_A_90DAY,
    STAKING_FLEXIBLE_180DAY:
      process.env.NEXT_PUBLIC_CONTRACT_STAKING_FLEXIBLE_180DAY,
    STAKING_FLEXIBLE_360DAY:
      process.env.NEXT_PUBLIC_CONTRACT_STAKING_FLEXIBLE_360DAY,
    BEP20: process.env.NEXT_PUBLIC_CONTRACT_BEP20,
    P2P_BINANCE: process.env.NEXT_PUBLIC_CONTRACT_P2P_BINANCE,
    P2P_POLYGON: process.env.NEXT_PUBLIC_CONTRACT_P2P_POLYGON,
    ESCAPE_URL: process.env.NEXT_PUBLIC_CONTRACT_ESCAPE_URL,
    BNB_CONTRACT: process.env.NEXT_PUBLIC_CONTRACT_BNB_CONTRACT
  },
  CHAIN: {
    POLYGON_SCAN: process.env.NEXT_PUBLIC_POLYGON_SCAN,
    POLYGON_RPC_URL: process.env.NEXT_PUBLIC_POLYGON_RPC_URL,
    TOKEN_NAME: process.env.NEXT_PUBLIC_TOKEN_NAME,
    TOKEN_SYMBOL: process.env.NEXT_PUBLIC_TOKEN_SYMBOL,
    TOKEN_NAME_BUSD: process.env.NEXT_PUBLIC_TOKEN_NAME_BUSD,
    TOKEN_SYMBOL_BNB: process.env.NEXT_PUBLIC_TOKEN_SYMBOL_BNB,
    CHAIN_ID: process.env.NEXT_PUBLIC_CHAIN_ID,
    CHAIN_ID_HEX: process.env.NEXT_PUBLIC_CHAIN_ID_HEX,
    CHAIN_ID_HEX_BNB: process.env.NEXT_PUBLIC_CHAIN_ID_HEX_BNB,
    CHAIN_NAME: process.env.NEXT_PUBLIC_CHAIN_NAME,
    BNB_CHAIN_ID: process.env.NEXT_PUBLIC_BNB_CHAIN_ID,
    BNB_CHAIN_NAME: process.env.NEXT_PUBLIC_BNB_CHAIN_NAME,
    BNB_RPC_URL: process.env.NEXT_PUBLIC_BNB_RPC_URL,
    BNB_SCAN: process.env.NEXT_PUBLIC_BNB_SCAN
  }
}

export default CONFIGS
