#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# git-format-staged -f 'prettier --ignore-unknown --stdin --stdin-filepath "{}"' .

# BY KAEN

echo "🧐 lint staged active..."
yarn lint-staged

yarn check-lint ||
(
  echo '🙅‍♀️🙅‍♀️🙅‍♀️ Get that weak shit out of here! 🙅‍♀️🙅‍♀️🙅‍♀️
    ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
  false;
)

# Building Tailwind CSS
yarn build:css ||
(
  echo '🎨🎨🎨 I am building the CSS 🎨🎨🎨'
  false;
)

# Format code.
echo "🤓 Formating code ... "
yarn format:prettier

# Check Prettier standards
yarn check:prettier ||
(
  echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
    Prettier Check Failed. Run [yarn format], add changes and try commit again.';
  false;
)
