#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# git-format-staged -f 'prettier --ignore-unknown --stdin --stdin-filepath "{}"' .

# BY KAEN

echo "🧐 lint staged active..."
yarn lint-staged

# Format code.
echo "🤓 Formating code ... "
yarn format

# Check Prettier standards  
yarn check-format ||

(
    echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run [yarn format], add changes and try commit again.';
    false;
)


# Check ESLint Standards
yarn check-eslint ||
(
        echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)