#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# pawaox4th@gmail.con

echo "⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼"
echo "🐙🐙🐙 RUN AS : $(date +%d/%m/%Y-%H:%M:%S) 🐙🐙🐙"
echo "⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼"
echo "👮☁️  Styling, linting, testing and building your project before committing [Pre-Push]
";

# Check tsconfig standards
yarn check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

yarn check-eslint ||
(
        echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# yarn check-eslint:dev ||
# (
#         echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
#                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
#         false; 
# )

yarn test ||
(
    echo '🔥🔥 Report from coverage 🔥🔥'
    false;
)

# # If everything passes... Now we can commit
# # echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

yarn build:dev ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# # If everything passes... Now we can commit
echo '🚀🚀🚀🚀 You win this time... I am pushed this now. 🚀'
echo "🐙🐙🐙 FINISH AT : $(date +%d/%m/%Y-%H:%M:%S) 🐙🐙🐙"
echo "⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼"